env:
  global:
    - secure: "C+UzJxsnPrj0VWA4NJNHNdJepCqij/fMllVpm3lZ/y3CMCMScF9pOv9ve+qRm5m1NyEUihEMVbILydP5iN2/hwncg1DJNTNCtJOgr0DoeYBf6d3sTC7TQS2HzPnK+pNgMLopk94cYNhwOU3eDaoYYqQ1YraysVDhdebRM5/u0o0="
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq build-essential dpkg-dev equivs reprepro
script:
- make all
